export const LIKE_EVENTS = {
  LIKE: {
    NEW: 'EVENT:LIKE.NEW',
    COMMENT: 'EVENT:LIKE.POST',
    POST: 'EVENT:LIKE.COMMENT',
  },
  DISLIKE: {
    NEW: 'EVENT:DISLIKE.NEW',
    COMMENT: 'EVENT:DISLIKE.POST',
    POST: 'EVENT:DISLIKE.COMMENT',
  },
};
