export const NODE_OBSERVABLE_REGISTER = {
  GENERIC: Symbol.for('MODULE:OBSERVABLE.NODE.GENERIC'),
  LIKE: Symbol.for('MODULE:OBSERVABLE.NODE.LIKE'),
  NOTIFICATION: Symbol.for('MODULE:OBSERVABLE.NODE.NOTIFICATION'),
};
