FROM node:18.18.2-slim

USER node

WORKDIR /home/node/app

COPY --chown=node:node ./twitter_clone/package*.json ./
RUN npm ci --legacy-peer-deps

COPY --chown=node:node ./twitter_clone ./

RUN npm run build

#CMD ["tail", "-f", "/dev/null"]
CMD ["npm", "run", "start"]
