FROM node:18.16.0-slim

USER node

WORKDIR /home/node/app

COPY --chown=node:node ./twitter_clone/package*.json ./
RUN npm ci

COPY --chown=node:node ./twitter_clone ./

#CMD ["tail", "-f", "/dev/null"]
CMD ["npm", "run", "build", "&&", "npm", "run", "start"]
