version: '3'

services:
  code_health:
    build:
      context: .
      dockerfile: Dockerfile.ci
    entrypoint: ['npm', 'run', 'code:ci']
    external_links:
      - 'host.docker.internal'
    depends_on:
      - api

  api:
    image: ghcr.io/samuel-ricardo/twitter_clone-api:main
    entrypoint: ['npm', 'run', 'start:docker']
    env_file:
      - .env.ci
    ports:
      - '3004:3000'
    external_links:
      - 'host.docker.internal'
    depends_on:
      - mongo_setup

  mongo:
    image: mongo:latest
    command: ['--replSet', 'rs0']
    ports:
      - '27017:27017'
    env_file:
      - .env.ci
    external_links:
      - 'host.docker.internal'

  mongo_setup:
    image: mongo
    depends_on:
      - mongo
    volumes:
      - ./.docker/mongo/scripts:/scripts
    entrypoint: ['bash', '/scripts/mongo_setup.sh']
    external_links:
      - 'host.docker.internal'
