version: '3'

services:
  code_health:
    build:
      context: .
      dockerfile: Dockerfile.ci
    entrypoint: ['npm', 'run', 'code:ci']
    external_links:
      - 'host.docker.internal'
    depends_on:
      - api
