version: '3'

services:
  twitter:
    build: .
    entrypoint: ['npm', 'run', 'start:docker']
    depends_on:
      - api
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
    external_links:
      - 'host.docker.internal'

    api:
      image: ghcr.io/samuel-ricardo/twitter_clone-api:main
      entrypoint: ['npm', 'run', 'start:docker']
      ports:
        - '3004:3000'
      env_file:
        - .env.ci
      external_links:
        - 'host.docker.intern'
