FROM node:18.16.0-slim

WORKDIR /home/node/app

COPY ./twitter_clone/package*.json ./
RUN ls -a
RUN npm ci

COPY ./twitter_clone/ ./
RUN npm run build

#CMD ["tail", "-f", "/dev/null"]
CMD ["npm", "run", "start"]
